**LIBRARIES**

**NUMPY**

In [ ]:
import numpy as np

In [ ]:
kanto = np.array([76,56,78])

In [ ]:
kanto

array([76, 56, 78])

In [ ]:
type(kanto)

numpy.ndarray

In [ ]:
w = np.array([1,2,3])
np.dot(kanto,w)

422

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1*arr2

array([ 4, 10, 18])

In [ ]:
arr3 = np.array([[11,12,13,14],
                [15,16,17,18],
                [19,20,11,12]])

In [ ]:
arr4 = np.array([[21,22,23,24],
                 [25,26,27,28],
                 [29,30,31,32]])

In [ ]:
arr3 + arr4

array([[32, 34, 36, 38],
       [40, 42, 44, 46],
       [48, 50, 42, 44]])

In [ ]:
#Adding a scaler
arr3 + 4

array([[15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 15, 16]])

In [ ]:
arr3 - arr4

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -20, -20]])

In [ ]:
arr3 * arr4

array([[231, 264, 299, 336],
       [375, 416, 459, 504],
       [551, 600, 341, 384]])

In [ ]:
arr3 % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [ ]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr1 = np.array([4,5,6,7])

In [ ]:
arr1.shape

(4,)

In [ ]:
arr1 +arr2

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [ ]:
arr5 = np.array([7,8])

In [ ]:
arr5.shape

(2,)

In [ ]:
arr1 = np.array([[1,2,3], [3,4,5]])
arr2 = np.array([[3,5,6],[7,8,9]])

In [ ]:
arr1 == arr2

array([[False, False, False],
       [False, False, False]])

In [ ]:
arr1 != arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr1 >= arr2

array([[False, False, False],
       [False, False, False]])

In [ ]:
arr1 < arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# ALL ZEROS
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# ALL ONES
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
#IDENTITY MATRIX
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#RANDOM VECTOR
np.random.rand(5)

array([0.91440296, 0.32432459, 0.50962614, 0.56420591, 0.42506138])

In [ ]:
# RANDOM METRIX
np.random.randn(2,3)

array([[-0.41187549, -0.21809141,  0.08784894],
       [ 0.90372503,  0.26163597,  1.32922723]])

In [ ]:
#FIXED VALUE
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [ ]:
#RANGE WITH START END AND STEP
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [ ]:
# EQUALLY SPACED NUMBER IN A RANGE
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [ ]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])